package com.example.composetemplate.managers

object StringsKeyManager {

    const val LOGIN_BUTTON = "LOGIN_BUTTON"
    const val REGISTER_BUTTON = "REGISTER_BUTTON"
    const val DONT_HAVE_ACCOUNT_TEXT = "DONT_HAVE_ACCOUNT_TEXT"
    const val AUTHENTICATION_ERROR_TEXT = "Authentication error - Please see all errors related to firebase auth"
    const val LOGIN_EMAIL_PLACEHOLDER = "LOGIN_EMAIL_PLACEHOLDER"
    const val LOGIN_PASSWORD_PLACEHOLDER = "LOGIN_PASSWORD_PLACEHOLDER"
    const val LOGIN_FULL_NAME_PLACEHOLDER = "LOGIN_FULL_NAME_PLACEHOLDER"
    const val LOGIN_CONFIRM_PASSWORD_PLACEHOLDER = "LOGIN_CONFIRM_PASSWORD_PLACEHOLDER"
    const val ALREADY_HAVE_ACCOUNT_TEXT = "ALREADY_HAVE_ACCOUNT_TEXT"
    const val LOGIN_WITH_GOOGLE = "LOGIN_WITH_GOOGLE"
    const val FORGOT_PASSWORD_TEXT = "Enter your email"
    const val FORGOT_PASSWORD_TITLE = "Forgot Password"
    const val FORGOT_PASSWORD_BUTTON_TEXT = "Send email"
    const val PAST_LECTURE_SUBTITLE = "PAST_LECTURE_SUBTITLE"
    const val NEXT_LECTURE_TITLE = "NEXT_LECTURE_TITLE"
    const val ONO_LECTURES_TEXT = "LECTURES_TITLE"
    const val PAST_LECTURE_SECTION_TITLE = "PAST_LECTURE_SECTION_TITLE"
    const val YES_BUTTON = "YES_BUTTON"
    const val NO_BUTTON = "NO_BUTTON"
    const val ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_LECTURE_MESSAGE = "ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_LECTURE_MESSAGE"
    const val USER_NOT_FOUND = "USER_NOT_FOUND_ERROR_MESSAGE"
    const val EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE_ERROR_MESSAGE"
    const val INVALID_PASSWORD = "WRONG_PASSWORD_ERROR_MESSAGE"
    const val NETWORK_ERROR = "NETWORK_ERROR_ERROR_MESSAGE"
    const val UNKNOWN_ERROR = "AUTH_DEFAULT_ERROR_MESSAGE"
    const val UNRESOLVED_ADDRESS_EXCEPTION = "Unresolved address exception."


    //EMPTY STATE
    const val EMPTY_STATE_PERMISSION_DENIED_TITLE = "EMPTY_STATE_PERMISSION_DENIED_TITLE"
    const val EMPTY_STATE_PERMISSION_DENIED_MESSAGE = "EMPTY_STATE_PERMISSION_DENIED_MESSAGE"
    const val EMPTY_STATE_NO_LECTURES_TITLE = "EMPTY_STATE_NO_LECTURES_TITLE"
    const val EMPTY_STATE_NO_LECTURES_MESSAGE = "EMPTY_STATE_NO_LECTURES_MESSAGE"
    const val EMPTY_STATE_SERVER_ERROR_TITLE = "EMPTY_STATE_SERVER_ERROR_TITLE"
    const val EMPTY_STATE_SERVER_ERROR_MESSAGE = "EMPTY_STATE_SERVER_ERROR_MESSAGE"
    const val EMPTY_STATE_NO_NETWORK_TITLE = "EMPTY_STATE_NO_NETWORK_TITLE"
    const val EMPTY_STATE_NO_NETWORK_MESSAGE = "EMPTY_STATE_NO_NETWORK_MESSAGE"

    //Firebase
    const val USER_NOT_FOUND_ERROR_MESSAGE = "USER_NOT_FOUND_ERROR_MESSAGE"
}
